#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0 on Sat Jan  1 21:05:53 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SearchFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SearchFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((546, 419))
        self.SetTitle("Dictionary Search by Letter")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_7.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.Search = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.Search, "Search")

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_2, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.Search, wx.ID_ANY, "Source Dictionary", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_2.Add(label_3, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.dictionary_selector = wx.ListBox(self.Search, wx.ID_ANY, choices=[])
        sizer_2.Add(self.dictionary_selector, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.Search, wx.ID_ANY, "Required Letters", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_4.Add(label_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.required_letter_selector = wx.CheckListBox(self.Search, wx.ID_ANY, choices=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])
        sizer_4.Add(self.required_letter_selector, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.Search, wx.ID_ANY, "Source Letters", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_5.Add(label_2, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.source_letter_selector = wx.CheckListBox(self.Search, wx.ID_ANY, choices=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])
        sizer_5.Add(self.source_letter_selector, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.search_button = wx.Button(self.Search, wx.ID_ANY, "Search")
        sizer_2.Add(self.search_button, 0, wx.ALL | wx.EXPAND, 10)

        static_line_1 = wx.StaticLine(self.Search, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_8.Add(static_line_1, 0, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_6, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.Search, wx.ID_ANY, "Found Words", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_6.Add(label_4, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.word_count_box = wx.TextCtrl(self.Search, wx.ID_ANY, "", style=wx.TE_DONTWRAP | wx.TE_LEFT | wx.TE_READONLY)
        sizer_6.Add(self.word_count_box, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.found_words_box = wx.TextCtrl(self.Search, wx.ID_ANY, "", style=wx.TE_DONTWRAP | wx.TE_LEFT | wx.TE_MULTILINE | wx.TE_READONLY)
        sizer_6.Add(self.found_words_box, 1, wx.ALL | wx.EXPAND, 10)

        self.Help = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.Help, "Help")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.help_box = wx.TextCtrl(self.Help, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_1.Add(self.help_box, 1, wx.ALL | wx.EXPAND, 0)

        self.Help.SetSizer(sizer_1)

        self.Search.SetSizer(sizer_8)

        self.panel_1.SetSizer(sizer_7)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, lambda event: self.on_search_button_pressed(), self.search_button)
        # end wxGlade

# end of class SearchFrame

class DictionarySearchGUI(wx.App):
    def OnInit(self):
        self.search_frame = SearchFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.search_frame)
        self.search_frame.Show()
        return True

# end of class DictionarySearchGUI

if __name__ == "__main__":
    dictionary_search_gui = DictionarySearchGUI(0)
    dictionary_search_gui.MainLoop()
