#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0 on Thu Dec 30 17:33:05 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SearchFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SearchFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((546, 419))
        self.SetTitle("Dictionary Search by Letter")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)

        self.dictionary_selector = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SORT)
        sizer_2.Add(self.dictionary_selector, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Required Letters", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_4.Add(label_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.key_letter_selection = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])
        sizer_4.Add(self.key_letter_selection, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Optional Letters", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_5.Add(label_2, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.optional_letter_selection = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])
        sizer_5.Add(self.optional_letter_selection, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.search_button = wx.Button(self.panel_1, wx.ID_ANY, "Search")
        sizer_2.Add(self.search_button, 0, wx.ALL | wx.EXPAND, 10)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_1.Add(static_line_1, 0, wx.EXPAND, 0)

        self.found_words_box = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_DONTWRAP | wx.TE_LEFT | wx.TE_MULTILINE | wx.TE_READONLY)
        sizer_1.Add(self.found_words_box, 1, wx.ALL | wx.EXPAND, 10)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, lambda event: self.on_search_button_pressed(), self.search_button)
        # end wxGlade

# end of class SearchFrame

class DictionarySearchGUI(wx.App):
    def OnInit(self):
        self.search_frame = SearchFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.search_frame)
        self.search_frame.Show()
        return True

# end of class DictionarySearchGUI

if __name__ == "__main__":
    dictionary_search_gui = DictionarySearchGUI(0)
    dictionary_search_gui.MainLoop()
